### ISSUE TITLE
your demo URL is not working 

### ISSUE THREAD

**Issue by shoaibch40** [MagnusThor/thor-io.vnext#2]
https://thorio.herokuapp.com/client/p2p.html#zkwjauzanz  

I tried this several times and didnt work for me

**Comment by MagnusThor** [comment]
Demo updated. Now working fine.

**Comment by shoaibch40** [comment]
sorry to bother still not working and here is the screenshot also tested on another friends laptop
http://screencast.com/t/1UtDfQlsc9R
