### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by shoaibch40** [MagnusThor/thor-io.vnext#3]
i installed your code after using this command 
npm install thor-io.vnext

it installed right with no biggie and few warnings which are also pasted below 

npm WARN enoent ENOENT: no such file or directory, open '/home/bitnami/shoaib/package.json'
npm WARN shoaib No description
npm WARN shoaib No repository field.
npm WARN shoaib No README data
npm WARN shoaib No license field.

then how do i run this what is the command what parameters should i use to run after this ?

**Comment by MagnusThor** [comment]
Just verified, installs fine.  You seems to lack a local package.config  ( in your folder )

-> run "npm init" to create a package.json file
-> run "npm install thor-io.vnext"
