### ISSUE TITLE
not running

### ISSUE THREAD

**Issue by shoaibch40** [MagnusThor/thor-io.vnext#4]
bitnami@ip-10-180-255-4:~/shoaib/node_modules$ npm start
npm ERR! Linux 3.13.0-92-generic
npm ERR! argv "/opt/bitnami/nodejs/bin/.node.bin" "/opt/bitnami/nodejs/bin/npm" "start"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3

npm ERR! missing script: start
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /home/bitnami/shoaib/node_modules/npm-debug.log
bitnami@ip-10-180-255-4:~/shoaib/node_modules$ ^C
bitnami@ip-10-180-255-4:~/shoaib/node_modules$

hi this issue trace

**Comment by MagnusThor** [comment]
When installing thor-io.vnext you get the framework, i suggest you clone/download the dev branch (#dev) https://github.com/MagnusThor/thor-io.vnext/tree/dev , as this includes the example you are looking for to try.  ( https://thorio.herokuapp.com/client/p2p.html) it works fine, but note there is no TURN config set up, so do a local test first , by using incognito windows also make sure you are using the complete url that the app gives you when you browse to it, as an example https://thorio.herokuapp.com/client/p2p.html#lynvolgzem  where #lynvolgzem is the room , okey?

Judging of you error, there is no start script, that is causes by the fact that you don't have one i  think
